Listar consultas reprogramadas para um dentista
dsnunes07/dentinhos-bootcamp pull request #7
Opened 2021-07-23 15:31 UTC by dsnunes07

Endpoint `turns/rescheduled/<dentist-id>` + testes

2021-07-23 15:33 UTC, CSiqueiraMeli approved these changes

2021-07-23 15:35 UTC, wesleyMeli approved these changes

2021-07-23 15:37 UTC, wesleyMeli requested changes
Check conflicts

2021-07-23 18:54 UTC, augusto-asilva approved these changes

2021-07-26 14:45 UTC, iBianquini approved these changes

2021-07-26 15:29 UTC, wesleyMeli approved these changes

2021-07-26 15:29 UTC, merged