Feat0002: Listar todos os dentistas que tenham mais de dois turnos em uma data
dsnunes07/dentinhos-bootcamp pull request #9
Opened 2021-07-23 21:13 UTC by CSiqueiraMeli

2021-07-26 12:08 UTC, augusto-asilva requested changes

2021-07-26 12:08 UTC, augusto-asilva commented on src/main/java/meli/bootcamp/dentinhos/service/DentistService.java
> +    public List<String> getTwoTurnsInOneDayAtDentist(Date data){
```suggestion
    public List<String> getTwoTurnsInOneDayForDentist(Date date){
```

2021-07-26 12:08 UTC, augusto-asilva commented on src/main/java/meli/bootcamp/dentinhos/controller/DentistController.java
> +       return dentistService.getTwoTurnsInOneDayAtDentist(data);
```suggestion
       return dentistService.getTwoTurnsInOneDayForDentist(date);
```

2021-07-26 12:08 UTC, augusto-asilva commented on src/main/java/meli/bootcamp/dentinhos/service/DentistService.java
> +        Date novaData = new Date(data.getTime() + (1000 * 60 * 60 * 24));
```suggestion
        Date newDate = new Date(date.getTime() + (1000 * 60 * 60 * 24));
```

2021-07-26 12:08 UTC, augusto-asilva commented on src/main/java/meli/bootcamp/dentinhos/service/DentistService.java
> +        return dentistRepository.dentists(novaData);
```suggestion
        return dentistRepository.dentists(newDate);
```

2021-07-26 14:46 UTC, iBianquini approved these changes

2021-07-26 15:27 UTC, wesleyMeli approved these changes

2021-07-26 19:05 UTC, augusto-asilva approved these changes

2021-07-26 19:06 UTC, dsnunes07 requested changes
corrigir apenas alguns typos nos nomes de funções

2021-07-26 19:06 UTC, dsnunes07 commented on src/main/java/meli/bootcamp/dentinhos/service/DentistService.java
> +    public List<String> getTwoTurnsInOneDayAtDentist(LocalDate date){
```suggestion
    public List<String> getTwoTurnsInOneDayForDentist(LocalDate date){
```

2021-07-26 19:06 UTC, dsnunes07 commented on src/test/java/meli/bootcamp/dentinhos/controller/DentistControllerTest.java
> +    void should_getDentistsNames_whitTwoTurnsInOneSpecificDay() throws Exception {
```suggestion
    void should_getDentistsNames_withTwoTurnsInSpecificDay() throws Exception {
```

2021-07-27 14:00 UTC, dsnunes07 approved these changes

2021-07-27 14:00 UTC, merged